In [1]:
import pandas

In [2]:
pandas.__version__

'2.2.3'

In [3]:
import numpy as np

In [4]:
mylist=[1,2,3]

In [5]:
type(mylist)


list

In [6]:
np.array(mylist)

array([1, 2, 3])

In [7]:
 mt=[[1,2,3],[4,5,6],[7,8,9]]

In [8]:
type(mt)


list

In [9]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [14]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
np.random.rand(1)

array([0.91685197])

In [18]:
np.random.rand(2,2)

array([[0.02399888, 0.61548795],
       [0.01521608, 0.27380469]])

In [19]:
np.random.randn(5)

array([ 1.05781499,  1.35233392, -0.20394612,  0.22501557, -0.29317713])

In [20]:
np.random.randint(1,1000,(5,5))

array([[ 27, 778, 431, 932, 814],
       [485, 347, 679, 667, 267],
       [332, 479, 852, 721,  93],
       [838, 231, 160, 120,  18],
       [ 24, 709, 253, 874, 286]])

In [6]:
np.random.seed(842)
np.random.rand(5)

array([0.63321185, 0.64663394, 0.85153518, 0.44240064, 0.5018913 ])

In [25]:
arr=np.arange(0,25)

In [28]:
arr.reshape(5,5
           )

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [29]:
arrr=np.random.randint(0,20,16)

In [8]:
arr=np.random.randint(0,25,12)
arr

array([24,  4,  9,  9, 12, 21, 21,  9,  2, 15,  9,  6])

In [31]:
arrr.max()

19

In [32]:
arrr.argmax()

2

In [34]:
arrr.min()

0

In [35]:
arrr.argmin()

3

In [36]:
t=np.arange(0,11)

In [37]:
t


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
t[:7]

array([0, 1, 2, 3, 4, 5, 6])

In [39]:
t[0:5]=1000

In [40]:
t

array([1000, 1000, 1000, 1000, 1000,    5,    6,    7,    8,    9,   10])

In [41]:
t=np.arange(0,11)

In [42]:
t

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
slice_of_t=t[0:5]

In [44]:
slice_of_t

array([0, 1, 2, 3, 4])

In [46]:
slice_of_t[1:4]=124

In [47]:
slice_of_t

array([  0, 124, 124, 124,   4])

In [48]:
t

array([  0, 124, 124, 124,   4,   5,   6,   7,   8,   9,  10])

In [49]:
cp=t.copy()

In [50]:
cp

array([  0, 124, 124, 124,   4,   5,   6,   7,   8,   9,  10])

In [51]:
cp[:]=100

In [52]:
cp

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [53]:
t

array([  0, 124, 124, 124,   4,   5,   6,   7,   8,   9,  10])

In [55]:
arr_2d=np.array([[4,5,12],[23,457,61]])

In [56]:
arr_2d


array([[  4,   5,  12],
       [ 23, 457,  61]])

In [59]:
arr_2d[1]

array([ 23, 457,  61])

In [61]:
arr_2d[1][2]

61

In [62]:
arr_2d[1,2]

61

In [63]:
arr_2d[:1,1:]

array([[ 5, 12]])

In [64]:
t >10

array([False,  True,  True,  True, False, False, False, False, False,
       False, False])

In [65]:
bool_arr=t >10

In [66]:
bool_arr

array([False,  True,  True,  True, False, False, False, False, False,
       False, False])

In [67]:
t[bool_arr]

array([124, 124, 124])

In [68]:
arr=np.arange(0,11)

In [70]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [71]:
arr+5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [72]:
arr-2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [73]:
arr *2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [74]:
arr/2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [75]:
1/arr

C:\Users\lenovo\AppData\Local\Temp\ipykernel_16708\255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [76]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [77]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [78]:
np.log(arr)

C:\Users\lenovo\AppData\Local\Temp\ipykernel_16708\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [79]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153])

In [80]:
np.tan(arr)

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128,
       -3.38051501, -0.29100619,  0.87144798, -6.79971146, -0.45231566,
        0.64836083])

In [81]:
np.arctan(arr)

array([0.        , 0.78539816, 1.10714872, 1.24904577, 1.32581766,
       1.37340077, 1.40564765, 1.42889927, 1.44644133, 1.46013911,
       1.47112767])

In [82]:
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [83]:
arr.mean()

5.0

In [84]:
arr2d=np.arange(0,25).reshape(5,5)

In [85]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [86]:
arr2d.max()

24

In [87]:
arr2d.sum(axis=0)

array([50, 55, 60, 65, 70])

In [88]:
arr2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])

In [2]:
import numpy as np

In [3]:
arr=np.arange(1,15)

In [4]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
np.array([1,2,3])

array([1, 2, 3])

In [9]:
cp=arr[0:5]

In [10]:
cp

array([24,  4,  9,  9, 12])

In [12]:
cp[0:5]=1215

In [13]:
cp

array([1215, 1215, 1215, 1215, 1215])

In [14]:
arr

array([1215, 1215, 1215, 1215, 1215,   21,   21,    9,    2,   15,    9,
          6])

In [15]:
cp=arr.copy()

In [16]:
cp

array([1215, 1215, 1215, 1215, 1215,   21,   21,    9,    2,   15,    9,
          6])

In [17]:
cp[:]=1215
cp

array([1215, 1215, 1215, 1215, 1215, 1215, 1215, 1215, 1215, 1215, 1215,
       1215])

In [18]:
arr

array([1215, 1215, 1215, 1215, 1215,   21,   21,    9,    2,   15,    9,
          6])

In [20]:
arr[arr<15]

array([9, 2, 9, 6])

In [22]:
import numpy as  np


In [25]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [26]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [72]:
np.ones(10)+4

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [32]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [33]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [45]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [38]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [39]:
np.random.rand(1)

array([0.69622481])

In [40]:
np.random.randn(25)

array([-0.3609599 , -0.57213131,  0.08558618,  0.38960487, -0.77419555,
        0.78002574,  1.27005267,  1.88004544, -0.3250575 ,  0.26274119,
       -0.25043683, -1.71063232, -0.09420562,  0.38261794,  0.26477154,
       -1.06925447,  0.24827132,  1.80913168, -1.2610535 ,  1.7079212 ,
        0.52823756, -0.56464519, -0.88854524, -0.59443186, -1.1313195 ])

In [44]:
np.arange(0.01,1.01,0.01).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [47]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [49]:
mat=np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [60]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [62]:
mat[3,4]

20

In [66]:
mat[:3,1].reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

In [67]:
    mat[4]

array([21, 22, 23, 24, 25])

In [68]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [69]:
mat.sum()

325

In [70]:
mat.std()

7.211102550927978

In [71]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])